# Generated by Django 5.0.2 on 2024-02-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vak_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesgever',
            name='id',
        ),
        migrations.AlterField(
            model_name='lesgever',
            name='lesgever_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
