# Generated by Django 5.0.2 on 2024-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lesgever_id_alter_lesgever_lesgever_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesgever',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='lesgevers_enrolled', to='api.vak'),
        ),
        migrations.AlterField(
            model_name='vak',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects_teachers', to='api.lesgever'),
        ),
    ]
