# Generated by Django 5.0.2 on 2024-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='vote_to_skip',
        ),
    ]
