name: Django CI

on:
  push:
    branches: [ "develop", "tests" ]
  pull_request:
    branches: [ "develop", "tests" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Linting API
      run: |
        flake8 ./api
    - name: Run Tests
      run: |
        python manage.py makemigrations api
        python manage.py migrate api
        python manage.py test
